# Generated by Django 3.2.15 on 2022-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='email address'),
        ),
    ]
