# Generated by Django 3.2.15 on 2022-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_alter_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='auth_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
