# Generated by Django 3.2.15 on 2022-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0003_alter_user_profile_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='moblie_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
