# Generated by Django 3.2.15 on 2022-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0005_alter_user_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
