# Generated by Django 3.2.15 on 2022-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0006_alter_user_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='is_active',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
